---
title: "DGP"
author: "Daniel Krasnov"
date: "2023-04-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# DGP
```{r Read in data}
# Read in data
forwardsfromgrandma <- read.csv("./Good datasets/forwardsfromgrandma.csv")
insaneparents <- read.csv("./Good datasets/insaneparents.csv")
news <- read.csv("./Good datasets/news.csv")
nothowgirlswork <- read.csv("./Good datasets/nothowgirlswork.csv")
vaxxhappened <- read.csv("./Good datasets/vaxxhappened.csv")
```

```{r}
# Set seed
set.seed(87460945)

# Construct Data Frames
idx <- sample(rownames(subset(forwardsfromgrandma,Sarcastic==1)),50)
FFG <- forwardsfromgrandma[idx,c("Body","Sarcastic")]

idx <- sample(rownames(subset(forwardsfromgrandma,Sarcastic==0)),450)
FFG <- rbind(FFG,forwardsfromgrandma[idx,c("Body","Sarcastic")])
 
idx <- sample(rownames(subset(insaneparents,Sarcastic==1)),50)
IP <- insaneparents[idx,c("Body","Sarcastic")]

idx <- sample(rownames(subset(insaneparents,Sarcastic==0)),450)
IP <- rbind(IP,insaneparents[idx,c("Body","Sarcastic")])

idx <- sample(rownames(subset(news,Sarcastic==1)),50)
new <- news[idx,c("Body","Sarcastic")]

idx <- sample(rownames(subset(news,Sarcastic==0)),450)
new <- rbind(new,news[idx,c("Body","Sarcastic")])

idx <- sample(rownames(subset(nothowgirlswork,Sarcastic==1)),50)
NHGW <- nothowgirlswork[idx,c("Body","Sarcastic")]

idx <- sample(rownames(subset(nothowgirlswork,Sarcastic==0)),450)
NHGW <- rbind(NHGW,nothowgirlswork[idx,c("Body","Sarcastic")])

idx <- sample(rownames(subset(vaxxhappened,Sarcastic==1)),50)
vax <- vaxxhappened[idx,c("Body","Sarcastic")]

idx <- sample(rownames(subset(vaxxhappened,Sarcastic==0)),450)
vax <- rbind(vax,vaxxhappened[idx,c("Body","Sarcastic")])
```

```{r Add dummy vars}
# FFG
FFG$FFG <- rep(1,500)
FFG$IP <- rep(0,500)
FFG$new <- rep(0,500)
FFG$NHGW <- rep(0,500)
FFG$vax <- rep(0,500)

# IP
IP$FFG <- rep(0,500)
IP$IP <- rep(1,500)
IP$new <- rep(0,500)
IP$NHGW <- rep(0,500)
IP$vax <- rep(0,500)

# new
new$FFG <- rep(0,500)
new$IP <- rep(0,500)
new$new <- rep(1,500)
new$NHGW <- rep(0,500)
new$vax <- rep(0,500)

# NHGW
NHGW$FFG <- rep(0,500)
NHGW$IP <- rep(0,500)
NHGW$new <- rep(0,500)
NHGW$NHGW <- rep(1,500)
NHGW$vax <- rep(0,500)

# vax
vax$FFG <- rep(0,500)
vax$IP <- rep(0,500)
vax$new <- rep(0,500)
vax$NHGW <- rep(0,500)
vax$vax <- rep(1,500)
```

```{r Make full data set}
data_full <- rbind(FFG,IP,new,NHGW,vax)
data_full$Body <- gsub("/s$", "", data_full$Body)
nrow(data_full)
```
```{r}
# Split data set in 2
idx_1 <- sample(1:2500,floor(2500/2))
idx_2 <- setdiff(1:2500,idx_1)

data_1 <- data_full[idx_1,]
data_2 <- data_full[idx_2,]

write.csv(data_1, "./split_1.csv", row.names=FALSE)
write.csv(data_2, "./split_2.csv", row.names=FALSE)

```


